FROM node:latest

# system local config
RUN true \
    # debian china mirrors
    && sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list \
    && sed -i 's/security.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list \
    # timezone to china
    && ln -sf /usr/share/zoneinfo/PRC /etc/localtime 

RUN apt-get update \
    && apt-get install -y \
    # node-sass 等编译依赖
    make gcc g++ python2.7 \
    # 命令行工具
    zsh curl wget vim git yarn xsel

# 切换 node 的软件版本源 => 切源工具 cgr 和 nrm
# cgr 是基于nrm的改进版本，进行了一些优化，能同时管理 npm、yarn 源
# cgr use taobao n => 只是切换 npm 源
# cgr use taobao y => 只是切换 yarn 源
RUN true \
    && npm install -g cgr nrm \
    && cgr use taobao \
    && yarn global add serve @vue/cli @vue/cli-service-global \
                commitizen conventional-changelog-cli eslint-plugin-vue \
                npm-check-updates npx

# 创建工作目录
RUN mkdir /workspace

WORKDIR /workspace

# 添加权限，755 或者 a+x
RUN chmod -R 755 /workspace

VOLUME /workspace

EXPOSE 8080  
EXPOSE 5000

CMD ["zsh"]